package burngormabs

import (
	"os"
	"path/filepath"
	"text/template"

	"github.com/ecoa-dev-team/burngormabs/utilities"
)

const unionTemplate = `// Code generated by generate_union.go; DO NOT EDIT.
package {{ .Package }}

type Model interface {
	{{- range $index, $type := .Types }}
	{{ if $index }}| {{ end }}{{ $type }}
	{{- end }}
}
`

func RepositoryGenerator() error {
	data := struct {
		Package string
		Types   []string
	}{
		Package: initialized.Package,
		Types:   []string{},
	}
	for _, _struct := range initialized.Models {
		_structInfo := utilities.GetStructInfo(_struct)
		data.Types = append(data.Types, _structInfo.Name)

	}

	dir := filepath.Dir(initialized.FileName)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	f, err := os.Create(initialized.FileName)
	if err != nil {
		return err
	}
	defer f.Close()

	tmpl := template.Must(template.New("union").Parse(unionTemplate))
	return tmpl.Execute(f, data)
}
