package burngormabs

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/ecoa-dev-team/burngormabs/utilities"
)

const unionTemplate = `// Code generated by "github.com/ecoa-dev-team/burngormabs; DO NOT EDIT.
package {{ .Package }}

import tools "github.com/ecoa-dev-team/burngormabs"

{{- range .Types }}
func New{{ . }}() *{{ . }} {
	t := &{{ . }}{}
	t.GenericCRUDImpl = tools.GenericCRUDImpl[{{ . }}]{Model: t} // Pass the outer struct reference
	return t
}
{{ end -}}
`

func (init *Init) RepositoryGenerator() error {
	data := struct {
		Package string
		Types   []string
	}{
		Package: init.Package,
		Types:   []string{},
	}
	for _, _struct := range init.Models {
		_structInfo := utilities.GetStructInfo(_struct)
		data.Types = append(data.Types, _structInfo.Name)

	}

	dir := filepath.Dir(init.FilePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	// Create file inside the directory
	// filepath.B/
	dst, err := os.Create(filepath.Join(dir, filepath.Base(init.FileName)))
	// fullPath := filepath.Join(dir, init.FileName)
	fmt.Println(dir)
	// f, err := os.Create(fullPath)
	if err != nil {
		return err
	}
	defer dst.Close()

	tmpl := template.Must(template.New("union").Parse(unionTemplate))
	return tmpl.Execute(dst, data)
}
